### PR TITLE
Add logo for Nextcloud settings page

### PR DESCRIPTION
**Pull request by ChristophBusold**
Create copy of logo without background and add it to settings page

### CODE REVIEW

**Comment by bud-mo** [comment]
Hello @ChristophBusold !
I will hold this pull request because we want to mainitain the compatibility with both Nextcloud and OwnCloud. I cannot find the `IIconSection` class in the OwnCloud codebase so I suspect the modification require a little of work to be merged.

There are two path I think we can take:
- Add a conditional code to load dinamically the OC or NC class.
- Build two separate apps, one for NC and one for OC.

**Comment by ChristophBusold** [comment]
This seems to work

**Comment by bud-mo** [comment]
Hello @ChristophBusold 
I have reviewed the PR and I am ready to merge it, please sign the CLA to allow me to proceed with the merge ;)

**Comment by ChristophBusold** [comment]
CLA is signed

**Comment by bud-mo** [comment]
@ChristophBusold Thankyou for the contribution!

**Pull request merged**
