### PR TITLE
Support for nextcloud 14

### PR DESCRIPTION
**Pull request by LarsN38**
Hello, 
It's a first post, so sorry if i have no post my question in good tab.

When zimbradrive work for nextcloud 14 ?

### CODE REVIEW

**Comment by xevilstar** [comment]
we need support for nextcloud 15

**Comment by gvargas9** [comment]
The workaround for NextCloud 15 and 14 is to edit file . zimbradrive/appinfo/info.xml

update
<dependencies>
        <nextcloud min-version="9" max-version="15"/>
    </dependencies>

**Comment by arza2008** [comment]
Hi, would like to ask? is there any plan to release an update for this extension? especially for nextcloud 14 and 15. Thanks.

**Comment by arza2008** [comment]
> The workaround for NextCloud 15 and 14 is to edit file . zimbradrive/appinfo/info.xml
> 
> update

How exactly? if i have remove the plugin [Zimbra_Drive] from Nextcloud server, and when I searching from the apps store in NC 14, the plugin doesn't appear as this plugin doesn't support yet in NC 14. Any manual/CLI way to install back? and clarify how actually editing the info.xml will solve the problem.

Thanks guys!

**Comment by bash2121** [comment]
Hello, thank you for tricks. I have edited info.xml and i can upgrade to nextcloud 14. But now, i have the check integrity error in my configuration. Why you don't release version 14 if it's just to edit info.xml ? ZimbraDrive still maintained for future versions of nextcloud? zimbradrive is not obselete? It's important to know, because for us, we have to choose between ldap and zimbradrive (and the migration is no easy).

**Comment by gvargas9** [comment]
I agree with you. I am not a developer, I just happened to have the same issue, so I end up finding a workaround.

**Comment by bud-mo** [comment]
Duplicate of #38

**Pull request closed without merging**
